In [1]:
import pickle
import pandas as pd
import numpy as np

In [31]:
with open('good.pickle', 'rb') as f:
    good = pickle.load(f)
with open('bad.pickle', 'rb') as f:
    bad = pickle.load(f)

In [32]:
good = good.sort_index(); good

,focus_gained,focus_lost,run,submit,text_insert,text_paste,text_remove,time_to_last,time_to_first,duration,coarse_time_on_task,fine_time_on_task,mean_latency
student,,,,,,,,,,,,,
0,335.0,327.0,94.0,30.0,4744.0,59.0,1068.0,6.321593e+05,7.063017e+05,74142.466667,427.965517,16403.0,2.485680
1,327.0,325.0,205.0,37.0,7050.0,45.0,1878.0,1.619366e+06,1.705339e+06,85972.709677,29270.806452,29665.0,3.028586
2,711.0,672.0,161.0,31.0,4660.0,80.0,894.0,8.689788e+05,1.510658e+06,641678.900000,8861.000000,25476.0,3.614130
3,100.0,89.0,0.0,30.0,284.0,28.0,156.0,2.789468e+06,2.789502e+06,33.612903,7.400000,1042.0,1.588415
4,311.0,310.0,82.0,39.0,4552.0,20.0,845.0,3.481572e+06,3.482497e+06,925.142857,833.333333,8897.0,1.451860
...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,168.0,166.0,74.0,31.0,5559.0,1.0,1346.0,3.317407e+06,3.333872e+06,16465.193548,3432.433333,13552.0,1.861538
445,507.0,448.0,213.0,30.0,16526.0,2.0,3101.0,3.403741e+06,3.543950e+06,140208.935484,473.533333,42809.0,2.067868
446,369.0,365.0,131.0,32.0,4122.0,114.0,1861.0,3.160902e+06,3.163844e+06,2942.233333,478.233333,16447.0,2.366815
447,359.0,336.0,129.0,30.0,5635.0,96.0,1149.0,6.727117e+05,7.080242e+05,35312.451613,220.200000,14618.0,1.908106
448,153.0,139.0,12.0,39.0,3597.0,42.0,679.0,3.293674e+06,3.557653e+06,263979.290323,122.933333,6197.0,1.340762

In [33]:
bad

,focus_gained,focus_lost,run,submit,text_insert,text_paste,text_remove,time_to_last,time_to_first,duration,coarse_time_on_task,fine_time_on_task,mean_latency
student,,,,,,,,,,,,,
0,335.0,327.0,94.0,30.0,4744.0,59.0,1068.0,6.321593e+05,7.063017e+05,74142.466667,427.965517,16403.0,2.485680
1,327.0,325.0,205.0,37.0,7050.0,45.0,1878.0,1.619366e+06,1.705339e+06,85972.709677,29270.806452,29665.0,3.028586
2,711.0,672.0,161.0,31.0,4660.0,80.0,894.0,8.689788e+05,1.510658e+06,641678.900000,8861.000000,25476.0,3.614130
3,100.0,89.0,0.0,30.0,284.0,28.0,156.0,2.789468e+06,2.789502e+06,33.612903,7.400000,1042.0,1.588415
4,311.0,310.0,82.0,39.0,4552.0,20.0,845.0,3.481572e+06,3.482497e+06,925.142857,833.333333,8897.0,1.451860
...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,168.0,166.0,74.0,31.0,5559.0,1.0,1346.0,3.317407e+06,3.333872e+06,16465.193548,3432.433333,13552.0,1.861538
445,507.0,448.0,213.0,30.0,16526.0,2.0,3101.0,3.403741e+06,3.543950e+06,140208.935484,473.533333,42809.0,2.067868
446,369.0,365.0,131.0,32.0,4122.0,114.0,1861.0,3.160902e+06,3.163844e+06,2942.233333,478.233333,16447.0,2.366815
447,359.0,336.0,129.0,30.0,5635.0,96.0,1149.0,6.727117e+05,7.080242e+05,35312.451613,220.200000,14618.0,1.908106
448,153.0,139.0,12.0,39.0,3597.0,42.0,679.0,3.293674e+06,3.557653e+06,263979.290323,122.933333,6197.0,1.340762

In [34]:
(good.sort_index().index == bad.index).all()

True

In [35]:
(good==bad).all(axis=0)

focus_gained           True
focus_lost             True
run                    True
submit                 True
text_insert            True
text_paste             True
text_remove            True
time_to_last           True
time_to_first          True
duration               True
coarse_time_on_task    True
fine_time_on_task      True
mean_latency           True
dtype: bool

In [36]:
with open('good_grades.pickle', 'rb') as f:
    good = pickle.load(f)
with open('bad_grades.pickle', 'rb') as f:
    bad = pickle.load(f)

In [38]:
(good == bad).all()

part1    True
part2    True
part3    True
part4    True
part5    True
part6    True
part7    True
exam1    True
exam2    True
exam3    True
final    True
dtype: bool